"""Load and normalize the customer support ticket dataset.

Source: Hugging Face `Tobi-Bueck/customer-support-tickets` (61,765 rows).
Raw schema: subject, body, answer, type, queue, priority, language, version,
tag_1..tag_8.

Assumptions (see also data/DATA_CARD.md, generated by this module):
- v1 filters to `language == "en"` only (28,261 of 61,765 rows). Non-English
  rows are dropped entirely, not translated.
- `body` is the actual ticket content; rows with null/empty body are dropped
  as unusable (1 such row in the English subset).
- `subject` may be null/empty (~13% of English rows); normalized to `""`
  rather than dropped, since a missing subject line doesn't make a ticket
  unusable.
- `answer` may be null (6 rows in the English subset); kept as
  `Optional[str]`. It is the dataset's real historical agent reply, used
  only as an evaluation reference — never as training data to imitate
  verbatim (per BUILD_PLAN.md).
- `queue` is non-null for every row in this dataset. If a future data
  refresh introduced a null/unrecognized `queue` value, that ticket would
  be routed to `Category.GENERAL_INQUIRY` at ingestion (logged, not
  silently dropped).
- `priority` in the English subset only takes {low, medium, high}; the
  full (multi-language) dataset also has {critical, very_low}. An
  unrecognized priority value raises `ValueError` rather than silently
  defaulting — mis-inferring urgency (e.g. downgrading a critical ticket)
  is worse than failing loudly.
- Ticket `id` is synthesized as `ticket-{row_index:06d}` over the
  English-filtered, body-non-empty rows (this dataset ships no native id).
- Dataset cache location: the `datasets` library's own default
  (`~/.cache/huggingface/datasets`, overridable via the `HF_DATASETS_CACHE`
  env var), NOT a `support_agent/data/cache/` dir as originally planned.
  On Windows, `datasets`' internal lock-file naming embeds the full
  resolved cache path twice in the lock filename; combined with this
  repo's own nested path, a repo-local cache dir exceeds Windows' 260-char
  `MAX_PATH` limit and fails with `FileNotFoundError`. The default cache
  is still local-only (no external service) and still gitignored via
  `HF_HOME`/`~/.cache`, satisfying the spirit of "cache locally" without
  hitting the path-length wall.
"""

from __future__ import annotations

from datasets import load_dataset

from support_agent.schemas import Category, Ticket, Urgency

DATASET_NAME = "Tobi-Bueck/customer-support-tickets"

# Maps the raw `queue` string to our normalized Category enum. Built from
# the exact 10 distinct queue values observed in the English-language rows.
QUEUE_TO_CATEGORY: dict[str, Category] = {
    "Technical Support": Category.TECHNICAL_SUPPORT,
    "Product Support": Category.PRODUCT_SUPPORT,
    "Customer Service": Category.CUSTOMER_SERVICE,
    "IT Support": Category.IT_SUPPORT,
    "Billing and Payments": Category.BILLING_AND_PAYMENTS,
    "Returns and Exchanges": Category.RETURNS_AND_EXCHANGES,
    "Service Outages and Maintenance": Category.SERVICE_OUTAGES_AND_MAINTENANCE,
    "Sales and Pre-Sales": Category.SALES_AND_PRE_SALES,
    "Human Resources": Category.HUMAN_RESOURCES,
    "General Inquiry": Category.GENERAL_INQUIRY,
}

# Maps the raw `priority` string to our normalized Urgency enum.
# very_low/critical only appear in non-English rows, out of scope for v1,
# but are mapped here for forward-compatibility.
PRIORITY_TO_URGENCY: dict[str, Urgency] = {
    "very_low": Urgency.LOW,
    "low": Urgency.LOW,
    "medium": Urgency.MEDIUM,
    "high": Urgency.HIGH,
    "critical": Urgency.CRITICAL,
}


def normalize_category(
    raw_queue: str | None, *, unknown_counter: dict[str, int] | None = None
) -> Category:
    """Map a raw `queue` string to Category, defaulting unknowns to GENERAL_INQUIRY."""
    if raw_queue is None or raw_queue not in QUEUE_TO_CATEGORY:
        if unknown_counter is not None:
            unknown_counter[raw_queue or "<null>"] = (
                unknown_counter.get(raw_queue or "<null>", 0) + 1
            )
        return Category.GENERAL_INQUIRY
    return QUEUE_TO_CATEGORY[raw_queue]


def normalize_urgency(raw_priority: str | None) -> Urgency:
    """Map a raw `priority` string to Urgency. Raises on unrecognized values."""
    if raw_priority not in PRIORITY_TO_URGENCY:
        raise ValueError(
            f"Unrecognized priority value: {raw_priority!r}. "
            "Update PRIORITY_TO_URGENCY in load_tickets.py before proceeding."
        )
    return PRIORITY_TO_URGENCY[raw_priority]


def load_and_normalize_tickets() -> list[Ticket]:
    """Load the HF dataset, filter to English, normalize into Ticket models.

    Uses the `datasets` library's default cache location (see module
    docstring for why this project does not override it with a repo-local
    directory). Prints a summary of rows dropped (empty body) and any
    unrecognized queue values encountered (routed to GENERAL_INQUIRY).
    """
    dataset = load_dataset(DATASET_NAME)["train"]
    english = dataset.filter(lambda row: row["language"] == "en")

    tickets: list[Ticket] = []
    dropped_empty_body = 0
    unknown_queues: dict[str, int] = {}

    for idx, row in enumerate(english):
        body = (row["body"] or "").strip()
        if not body:
            dropped_empty_body += 1
            continue

        answer = row["answer"].strip() if row["answer"] else None
        tickets.append(
            Ticket(
                id=f"ticket-{idx:06d}",
                subject=(row["subject"] or "").strip(),
                body=body,
                answer=answer or None,
                category=normalize_category(row["queue"], unknown_counter=unknown_queues),
                urgency=normalize_urgency(row["priority"]),
                language=row["language"],
                ticket_type=row["type"],
                raw_queue=row["queue"],
                raw_priority=row["priority"],
            )
        )

    print(f"[load_tickets] English rows: {len(english)}")
    print(f"[load_tickets] Dropped (empty body): {dropped_empty_body}")
    print(f"[load_tickets] Normalized tickets: {len(tickets)}")
    if unknown_queues:
        print(
            f"[load_tickets] WARNING — unrecognized queue values routed to GENERAL_INQUIRY: {unknown_queues}"
        )

    return tickets


if __name__ == "__main__":
    load_and_normalize_tickets()
